In [1]:
import numpy as np

In [30]:
L = 2*np.pi
Nk = 17
Nx = 2*(Nk-1)
dx = L/Nx
xs = np.linspace(0,L,Nx+1)

In [31]:
xs

array([0.        , 0.19634954, 0.39269908, 0.58904862, 0.78539816,
       0.9817477 , 1.17809725, 1.37444679, 1.57079633, 1.76714587,
       1.96349541, 2.15984495, 2.35619449, 2.55254403, 2.74889357,
       2.94524311, 3.14159265, 3.33794219, 3.53429174, 3.73064128,
       3.92699082, 4.12334036, 4.3196899 , 4.51603944, 4.71238898,
       4.90873852, 5.10508806, 5.3014376 , 5.49778714, 5.69413668,
       5.89048623, 6.08683577, 6.28318531])

In [32]:
xs[1]-xs[0]

0.19634954084936207

In [33]:
np.pi * np.abs(np.fft.fftfreq(Nx))

array([0.        , 0.09817477, 0.19634954, 0.29452431, 0.39269908,
       0.49087385, 0.58904862, 0.68722339, 0.78539816, 0.88357293,
       0.9817477 , 1.07992247, 1.17809725, 1.27627202, 1.37444679,
       1.47262156, 1.57079633, 1.47262156, 1.37444679, 1.27627202,
       1.17809725, 1.07992247, 0.9817477 , 0.88357293, 0.78539816,
       0.68722339, 0.58904862, 0.49087385, 0.39269908, 0.29452431,
       0.19634954, 0.09817477])

In [46]:
np.abs(np.fft.fftfreq(Nx))[0:Nk]

array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    ])

In [37]:
print(len(np.fft.fftfreq(Nx)))
print(len(np.fft.fftfreq(Nx)[0:Nk]))

32
17


In [45]:
np.fft.rfftfreq(Nx)

array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    ])